### ISSUE TITLE
See list of sessions

### ISSUE THREAD

**Issue by fbiville** [Agatesse/hackergarten-session#1]
_Unsure who Dilara, Samuel or Cathy are? Check out our [personas](https://github.com/Agatesse/hackergarten-session/wiki/Personas)._

Dilara can see the list of registered sessions.

**Acceptance criteria:**
- when I successfully log in with my project lead account, I am redirected to the list of registered sessions
- if no sessions are registered, I should see that the message "No session found"

**Comment by fbiville** [comment]
Technical TODO:

- [x] bootstrap backend with session API
- [x] bootstrap frontend with basic session page
- [x] connect frontend to backend
- [x] add LICENSE
- [x] complete README
- [x] extract Venue as standalone entity
- [ ] set up auth
     - [x] restrict API to LEAD users
     - [ ] update curl examples in README
     - [ ] set up login and protect session frontend page
- [ ] set up Flyway to initialize database
- [ ] add profile to init local backend with data for frontend e2e tests
- [ ] integrate Bootstrap for basic design
- [ ] deploy to PCF
- [ ] set up continuous integration and deployment
